version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: ${MONGO_DB}
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongodb_data:

